### PR TITLE
Home page improvements 239

### PR DESCRIPTION
**Pull request by Kwood22**
Feel free to give opinions and suggestions.

### CODE REVIEW

**Comment by Kwood22** [comment]
I have made changes to responsiveness as well as made the text left-align

**Comment by steichert** [comment]
Looks much better! The only other thing is there isn't much spacing between the buttons, and the title looks a bit off-centre compared to the rest of the text.

**Comment by SpellBreakerZA** [comment]
> Looks much better! The only other thing is there isn't much spacing between the buttons, and the title looks a bit off-centre compared to the rest of the text.

Maybe posting a screenshot could help explain the situation better?

**Comment by SpellBreakerZA** [comment]
Kyle, do since you are making changes to the front-end can I ask that you add the Linux Steam route to the walkthrough? 
Apparently, it's ~/.steam/steam/SteamApps/common but I cannot say for sure

Reference
https://askubuntu.com/questions/227502/where-are-steam-games-installed

**Comment by steichert** [comment]
screenshot 2018-10-15 at 18 05 13

**Comment by SpellBreakerZA** [comment]
I have a problem... The heroes images don't load on my pc

**Comment by SpellBreakerZA** [comment]
> I have a problem... The heroes images don't load on my pc

I would have been nice to know that I had to remigrate and rescrape... :sweat:

**Comment by SpellBreakerZA** [comment]
But I have a strange issue. A popover appears above an item, but also in the top left corner of the screen too...

**Comment by Kwood22** [comment]
@SpellBreakerZA  I cannot seem to replicate your popover issue, I have added the linux path to the tutorial page

**Comment by SpellBreakerZA** [comment]
I am working on some other aspect of the system currently. I think that I hovered over a bought item and then over the items in the selection list

**Comment by Kwood22** [comment]
@SpellBreakerZA  I tried what you suggested. I still cannot replicate it :\

**Comment by SpellBreakerZA** [comment]
In the read me section of the bot config heroes tab, let the users know that they have to have 5 bots selected else there will be empty slots...

**Comment by SpellBreakerZA** [comment]
In fact the game crashes if they have less than 5 heroes, so we need to enforce it on the front-end, if possible

**Comment by SpellBreakerZA** [comment]
Is there a Linux and mac version of the install script? Do you provide a checksum?

**Comment by Kwood22** [comment]
@SpellBreakerZA  There are Windows, mac and Linux installer scripts, Linux and Mac work. Need to test the windows version.

**Comment by SpellBreakerZA** [comment]
Can I merge this pull request? Everybody approved. So there are no grievances?

**Pull request merged**
